### ISSUE TITLE
testing triage-new-issues app

### ISSUE THREAD

**Issue by tunnckoCore** [olstenlarck/probot-test#10]
ho ho ho! the bot should add `triage` label to that issue :tada:

**Comment by tunnckoCore** [comment]
yup

**Comment by olstenlarck** [comment]
reopen issue without labels should add `triage` label again

**Comment by tunnckoCore** [comment]
reopening an issue without labels should add `triage` label again

**Comment by tunnckoCore** [comment]
nah.. typo in source code of the app ;d

**Comment by tunnckoCore** [comment]
reopening an issue without labels should add `triage` label again

**Comment by tunnckoCore** [comment]
yup. app is finished ;d
